/* eslint-disable */
import { gql, type TypedDocumentNode } from '@apollo/client/core';
import * as Apollo from '@apollo/client/react';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions = {} as const;
/** Auto-generated by manual authoring to mirror codegen output. Re-run `npm run codegen` against a live backend to refresh. */
export type Product = {
  __typename?: 'Product';
  id: string;
  name: string;
  sku: string;
  price: number;
  slug: string;
  description: string;
  thumbnailUrl?: Maybe<string>;
  stock?: Maybe<number>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  endCursor?: Maybe<string>;
  hasNextPage: boolean;
};

export type ProductConnection = {
  __typename?: 'ProductConnection';
  edges: Array<{ __typename?: 'ProductEdge'; node: Product }>;
  totalCount: number;
  pageInfo: PageInfo;
};

export type CartItem = {
  __typename?: 'CartItem';
  id: string;
  productId: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  product?: Maybe<Product>;
};

export type Cart = {
  __typename?: 'Cart';
  id: string;
  subtotal: number;
  total: number;
  items: CartItem[];
};

export type Order = {
  __typename?: 'Order';
  id: string;
  orderNumber: string;
  status: string;
  total: number;
  createdAt: string;
};

export type OrderConnection = {
  __typename?: 'OrderConnection';
  edges: Array<{ __typename?: 'OrderEdge'; node: Order }>;
};

export type User = {
  __typename?: 'User';
  id: string;
  email: string;
  role: string;
  firstName?: Maybe<string>;
  lastName?: Maybe<string>;
};

export type AuthPayload = {
  __typename?: 'AuthPayload';
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: User;
};

export type Scalars = {
  ID: string;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  JSON: Record<string, unknown>;
};

export type GetProductsQuery = {
  products?: Maybe<ProductConnection>;
};

export type GetProductsQueryVariables = Exact<{
  first?: InputMaybe<number>;
  after?: InputMaybe<string>;
}>;

export type GetProductQuery = {
  product?: Maybe<Product>;
};

export type GetProductQueryVariables = Exact<{ slug: Scalars['String'] }>;

export type GetMeQuery = { me?: Maybe<User> };

export type GetMeQueryVariables = Exact<{ [key: string]: never }>;

export type GetCartQuery = { cart?: Maybe<Cart> };

export type GetCartQueryVariables = Exact<{ [key: string]: never }>;

export type GetOrdersQuery = { orders?: Maybe<OrderConnection> };

export type GetOrdersQueryVariables = Exact<{ [key: string]: never }>;

export type LoginMutation = { login: AuthPayload };

export type LoginMutationVariables = Exact<{
  email: Scalars['String'];
  password: Scalars['String'];
}>;

export type RegisterMutation = { register: AuthPayload };

export type RegisterMutationVariables = Exact<{
  email: Scalars['String'];
  password: Scalars['String'];
  firstName?: InputMaybe<Scalars['String']>;
  lastName?: InputMaybe<Scalars['String']>;
}>;

export type RefreshTokenMutation = {
  refreshToken: Pick<AuthPayload, 'accessToken' | 'refreshToken' | 'expiresIn'>;
};

export type RefreshTokenMutationVariables = Exact<{ token: Scalars['String'] }>;

export type AddToCartMutation = { addToCart: Cart };

export type AddToCartMutationVariables = Exact<{
  productId: Scalars['String'];
  quantity: Scalars['Int'];
}>;

export type RemoveFromCartMutation = { removeFromCart: Cart };

export type RemoveFromCartMutationVariables = Exact<{ itemId: Scalars['String'] }>;

export type CreateOrderMutation = {
  createOrder: Pick<Order, 'id' | 'orderNumber' | 'status' | 'total'>;
};

export type CreateOrderMutationVariables = Exact<{
  shippingAddress: Scalars['JSON'];
}>;

export const GetProductsDocument = gql`
  query GetProducts($first: Int, $after: String) {
    products(pagination: { first: $first, after: $after }) {
      edges {
        node {
          id
          name
          sku
          price
          slug
          description
          thumbnailUrl
        }
      }
      totalCount
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
` as unknown as TypedDocumentNode<GetProductsQuery, GetProductsQueryVariables>;

export const GetProductDocument = gql`
  query GetProduct($slug: String!) {
    product(slug: $slug) {
      id
      name
      sku
      price
      slug
      description
      thumbnailUrl
      stock
    }
  }
` as unknown as TypedDocumentNode<GetProductQuery, GetProductQueryVariables>;

export const GetMeDocument = gql`
  query GetMe {
    me {
      id
      email
      role
      firstName
      lastName
    }
  }
` as unknown as TypedDocumentNode<GetMeQuery, GetMeQueryVariables>;

export const GetCartDocument = gql`
  query GetCart {
    cart {
      id
      subtotal
      total
      items {
        id
        productId
        quantity
        unitPrice
        totalPrice
        product {
          id
          name
          thumbnailUrl
        }
      }
    }
  }
` as unknown as TypedDocumentNode<GetCartQuery, GetCartQueryVariables>;

export const GetOrdersDocument = gql`
  query GetOrders {
    orders {
      edges {
        node {
          id
          orderNumber
          status
          total
          createdAt
        }
      }
    }
  }
` as unknown as TypedDocumentNode<GetOrdersQuery, GetOrdersQueryVariables>;

export const LoginDocument = gql`
  mutation Login($email: String!, $password: String!) {
    login(input: { email: $email, password: $password }) {
      accessToken
      refreshToken
      expiresIn
      user {
        id
        email
        role
      }
    }
  }
` as unknown as TypedDocumentNode<LoginMutation, LoginMutationVariables>;

export const RegisterDocument = gql`
  mutation Register(
    $email: String!
    $password: String!
    $firstName: String
    $lastName: String
  ) {
    register(
      input: {
        email: $email
        password: $password
        firstName: $firstName
        lastName: $lastName
      }
    ) {
      accessToken
      refreshToken
      expiresIn
      user {
        id
        email
        role
      }
    }
  }
` as unknown as TypedDocumentNode<RegisterMutation, RegisterMutationVariables>;

export const RefreshTokenDocument = gql`
  mutation RefreshToken($token: String!) {
    refreshToken(token: $token) {
      accessToken
      refreshToken
      expiresIn
    }
  }
` as unknown as TypedDocumentNode<RefreshTokenMutation, RefreshTokenMutationVariables>;

export const AddToCartDocument = gql`
  mutation AddToCart($productId: String!, $quantity: Int!) {
    addToCart(input: { productId: $productId, quantity: $quantity }) {
      id
      subtotal
      total
      items {
        id
        productId
        quantity
        unitPrice
        totalPrice
      }
    }
  }
` as unknown as TypedDocumentNode<AddToCartMutation, AddToCartMutationVariables>;

export const RemoveFromCartDocument = gql`
  mutation RemoveFromCart($itemId: String!) {
    removeFromCart(input: { itemId: $itemId }) {
      id
      subtotal
      total
      items {
        id
        productId
        quantity
        unitPrice
        totalPrice
      }
    }
  }
` as unknown as TypedDocumentNode<RemoveFromCartMutation, RemoveFromCartMutationVariables>;

export const CreateOrderDocument = gql`
  mutation CreateOrder($shippingAddress: JSON!) {
    createOrder(input: { shippingAddress: $shippingAddress }) {
      id
      orderNumber
      status
      total
    }
  }
` as unknown as TypedDocumentNode<CreateOrderMutation, CreateOrderMutationVariables>;

export type { TypedDocumentNode };

export function useGetProductsQuery(
  options?: Apollo.QueryHookOptions<GetProductsQuery, GetProductsQueryVariables>
) {
  return Apollo.useQuery<GetProductsQuery, GetProductsQueryVariables>(
    GetProductsDocument,
    { ...defaultOptions, ...options }
  );
}

export function useGetProductQuery(
  options: Apollo.QueryHookOptions<GetProductQuery, GetProductQueryVariables>
) {
  return Apollo.useQuery<GetProductQuery, GetProductQueryVariables>(
    GetProductDocument,
    { ...defaultOptions, ...options }
  );
}

export function useGetMeQuery(
  options?: Apollo.QueryHookOptions<GetMeQuery, GetMeQueryVariables>
) {
  return Apollo.useQuery<GetMeQuery, GetMeQueryVariables>(GetMeDocument, {
    ...defaultOptions,
    ...options,
  });
}

export function useGetCartQuery(
  options?: Apollo.QueryHookOptions<GetCartQuery, GetCartQueryVariables>
) {
  return Apollo.useQuery<GetCartQuery, GetCartQueryVariables>(GetCartDocument, {
    ...defaultOptions,
    ...options,
  });
}

export function useGetOrdersQuery(
  options?: Apollo.QueryHookOptions<GetOrdersQuery, GetOrdersQueryVariables>
) {
  return Apollo.useQuery<GetOrdersQuery, GetOrdersQueryVariables>(GetOrdersDocument, {
    ...defaultOptions,
    ...options,
  });
}

export function useLoginMutation(
  options?: Apollo.MutationHookOptions<LoginMutation, LoginMutationVariables>
) {
  return Apollo.useMutation<LoginMutation, LoginMutationVariables>(
    LoginDocument,
    options
  );
}

export function useRegisterMutation(
  options?: Apollo.MutationHookOptions<RegisterMutation, RegisterMutationVariables>
) {
  return Apollo.useMutation<RegisterMutation, RegisterMutationVariables>(
    RegisterDocument,
    options
  );
}

export function useRefreshTokenMutation(
  options?: Apollo.MutationHookOptions<RefreshTokenMutation, RefreshTokenMutationVariables>
) {
  return Apollo.useMutation<RefreshTokenMutation, RefreshTokenMutationVariables>(
    RefreshTokenDocument,
    options
  );
}

export function useAddToCartMutation(
  options?: Apollo.MutationHookOptions<AddToCartMutation, AddToCartMutationVariables>
) {
  return Apollo.useMutation<AddToCartMutation, AddToCartMutationVariables>(
    AddToCartDocument,
    options
  );
}

export function useRemoveFromCartMutation(
  options?: Apollo.MutationHookOptions<RemoveFromCartMutation, RemoveFromCartMutationVariables>
) {
  return Apollo.useMutation<RemoveFromCartMutation, RemoveFromCartMutationVariables>(
    RemoveFromCartDocument,
    options
  );
}

export function useCreateOrderMutation(
  options?: Apollo.MutationHookOptions<CreateOrderMutation, CreateOrderMutationVariables>
) {
  return Apollo.useMutation<CreateOrderMutation, CreateOrderMutationVariables>(
    CreateOrderDocument,
    options
  );
}

export type GetProductsSuspenseQueryHookResult = ReturnType<
  typeof Apollo.useSuspenseQuery<GetProductsQuery, GetProductsQueryVariables>
>;
export type GetProductsQueryHookResult = ReturnType<typeof useGetProductsQuery>;
export type GetProductsQueryResult = Apollo.QueryResult<GetProductsQuery, GetProductsQueryVariables>;

export type GetProductSuspenseQueryHookResult = ReturnType<
  typeof Apollo.useSuspenseQuery<GetProductQuery, GetProductQueryVariables>
>;
export type GetProductQueryHookResult = ReturnType<typeof useGetProductQuery>;
export type GetProductQueryResult = Apollo.QueryResult<GetProductQuery, GetProductQueryVariables>;

export type GetMeSuspenseQueryHookResult = ReturnType<
  typeof Apollo.useSuspenseQuery<GetMeQuery, GetMeQueryVariables>
>;
export type GetMeQueryHookResult = ReturnType<typeof useGetMeQuery>;
export type GetMeQueryResult = Apollo.QueryResult<GetMeQuery, GetMeQueryVariables>;

export type GetCartSuspenseQueryHookResult = ReturnType<
  typeof Apollo.useSuspenseQuery<GetCartQuery, GetCartQueryVariables>
>;
export type GetCartQueryHookResult = ReturnType<typeof useGetCartQuery>;
export type GetCartQueryResult = Apollo.QueryResult<GetCartQuery, GetCartQueryVariables>;

export type GetOrdersSuspenseQueryHookResult = ReturnType<
  typeof Apollo.useSuspenseQuery<GetOrdersQuery, GetOrdersQueryVariables>
>;
export type GetOrdersQueryHookResult = ReturnType<typeof useGetOrdersQuery>;
export type GetOrdersQueryResult = Apollo.QueryResult<GetOrdersQuery, GetOrdersQueryVariables>;

export type LoginMutationHookResult = ReturnType<typeof useLoginMutation>;
export type LoginMutationResult = Apollo.MutationResult<LoginMutation>;
export type LoginMutationOptions = Apollo.MutationFunctionOptions<LoginMutation, LoginMutationVariables>;

export type RegisterMutationHookResult = ReturnType<typeof useRegisterMutation>;
export type RegisterMutationResult = Apollo.MutationResult<RegisterMutation>;
export type RegisterMutationOptions = Apollo.MutationFunctionOptions<RegisterMutation, RegisterMutationVariables>;

export type RefreshTokenMutationHookResult = ReturnType<typeof useRefreshTokenMutation>;
export type RefreshTokenMutationResult = Apollo.MutationResult<RefreshTokenMutation>;
export type RefreshTokenMutationOptions = Apollo.MutationFunctionOptions<RefreshTokenMutation, RefreshTokenMutationVariables>;

export type AddToCartMutationHookResult = ReturnType<typeof useAddToCartMutation>;
export type AddToCartMutationResult = Apollo.MutationResult<AddToCartMutation>;
export type AddToCartMutationOptions = Apollo.MutationFunctionOptions<AddToCartMutation, AddToCartMutationVariables>;

export type RemoveFromCartMutationHookResult = ReturnType<typeof useRemoveFromCartMutation>;
export type RemoveFromCartMutationResult = Apollo.MutationResult<RemoveFromCartMutation>;
export type RemoveFromCartMutationOptions = Apollo.MutationFunctionOptions<RemoveFromCartMutation, RemoveFromCartMutationVariables>;

export type CreateOrderMutationHookResult = ReturnType<typeof useCreateOrderMutation>;
export type CreateOrderMutationResult = Apollo.MutationResult<CreateOrderMutation>;
export type CreateOrderMutationOptions = Apollo.MutationFunctionOptions<CreateOrderMutation, CreateOrderMutationVariables>;
